httpclient:
  ##################### SSL的配置  ###############################
  sslVersion: SSLv3

  ######################   连接池的配置   ##############################
  # 最大连接数
  connectMax: 10
  # 每个路由基本连接数
  connectRoute: 10
  # 获取连接池连接的超时时间（ms）
  requestTimeOut: 10000

  #####################     请求的配置       ###########################
  # 建立请求的超时时间, 是在建立TCP连接之前的超时（ms）
  connectTimeOut: 10000
  # Socket超时时间，设置数据传输后等待响应的超时时间, 是在TCP连接建立之后的超时（ms）
  socketTimeOut: 120000

  ########################   重试机制的配  ############################
  # 重试次数
  retryTime: 3

